-- GLOBAL SUPPLY CHAIN AND INVENTORY OPTIMIZATION ANALYTICS

-- CREATING DATABASE AND IMPORTING DATA FROM PYTHON FOR DEEPER ANALYSIS
CREATE DATABASE SUPPLY_CHAIN_PROJECT;
USE SUPPLY_CHAIN_PROJECT;

-- ANSWERING BUSINESS QUESTIONS

-- 1. TOTAL REVENUE BY REGION
SELECT
    REGION,
    ROUND(
        SUM(HISTORICAL_SALES * PRODUCT_PRICE * (1 - DISCOUNT_RATE)),
        2
    ) AS TOTAL_REVENUE
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY TOTAL_REVENUE DESC;

-- INSIGHT: LATIN AMERICA GENERATES THE HIGHEST REVENUE OF $1583428087.41 FOLLOWED BY EUROPE, 
--          ASIA PACIFIC NORTH AMERICA AND MIDDLE EAST WHICH GENERATES THE LEAST REVENUE OF 1539381938.98, BUT ALL REGIONS HAVE SIMILAR TOTAL REVENUE.


-- 2. AVERAGE MARKETING SPEND BY PRODUCT CATEGORY
SELECT PRODUCT_CATEGORY, ROUND(AVG(MARKETING_SPEND),2) AS AVERAGE_MARKETING_SPEND
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY AVERAGE_MARKETING_SPEND DESC;

-- INSIGHT: EVERY PRODUCT CATEGORY HAS SIMILAR AVERAGE MARKETING SPEND BUT THE BEAUTY CATEGORY HAS THE HIGHEST AVERAGE MARKETING SPEND, $5296.72, 
--          FOLLOWED BY ELECTRONICS, HOME, AND FASHION, WHILE THE SPORTS CATEGORY RECEIVES THE LOWEST AVERAGE MARKETING INVESTMENT OF $5232.76.


-- 3. TOTAL NUMBER OF ORDERS BY CUSTOMER SEGMENT
SELECT CUSTOMER_SEGMENT, COUNT(ORDER_ID) AS TOTAL_NUMBER_OF_ORDERS
FROM SUPPLY_DATA
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_NUMBER_OF_ORDERS DESC;

-- INSIGHT: WHOLESALE AND RETAIL CUSTOMER SEGMENTS CONTRIBUTE EQUALLY TO ORDER VOLUME, WITH THE WHOLESALE SEGMENT LEADING SLIGHTLY AT 12,527 ORDERS 
--          COMPARED TO 12,473 ORDERS FROM RETAIL.


-- 4. AVERAGE DISCOUNT RATE OFFERED 
-- 4.1 AVERAGE DISCOUNT RATE OFFERED BY EACH BRAND
SELECT BRAND, ROUND(AVG(DISCOUNT_RATE)*100,2) AS AVG_DISCOUNT
FROM SUPPLY_DATA
GROUP BY BRAND
ORDER BY AVG_DISCOUNT;

-- 4.2 -- AVERAGE DISCOUNT BY PRODUCT CATEGORY
SELECT PRODUCT_CATEGORY,
    ROUND(AVG(DISCOUNT_RATE) * 100, 2) AS AVG_DISCOUNT_PERCENT
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY AVG_DISCOUNT_PERCENT DESC;

-- 4.3 AVERAGE DISCOUNT BY CUSTOMER SEGMENT
SELECT CUSTOMER_SEGMENT,
    ROUND(AVG(DISCOUNT_RATE) * 100, 2) AS AVG_DISCOUNT_PERCENT
FROM SUPPLY_DATA
GROUP BY CUSTOMER_SEGMENT
ORDER BY AVG_DISCOUNT_PERCENT DESC;

-- INSIGHT: THE AVERAGE DISCOUNT PERCENTAGE REMAINS NEARLY IDENTICAL ACROSS ALL BRANDS, PRODUCT CATEGORIES, AND CUSTOMER SEGMENTS.

-- 5. DOES HIGHER DISCOUNT GENERATE MORE SALES?
SELECT
    CASE
        WHEN DISCOUNT_RATE < 0.10 THEN 'LOW'
        WHEN DISCOUNT_RATE < 0.20 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS DISCOUNT_GROUP,
    ROUND(AVG(HISTORICAL_SALES), 2) AS AVG_SALES
FROM SUPPLY_DATA
GROUP BY DISCOUNT_GROUP;
-- INSIGHT: AVERAGE SALES ARE ALMOST SAME FOR ALL DISCOUNT GROUPS WHICH SIGNIFIES THAT DISCOUNT HAS VERY LITTLE EFFECT ON THE VOLUME OF SALES.


-- 6. COMPARISON OF AVERAGE COMPANY PRICE VS AVERAGE COMPETITOR PRICE BY CATEGORY
SELECT PRODUCT_CATEGORY,ROUND(AVG(PRODUCT_PRICE),2) AS AVG_COMPANY_PRICE, ROUND(AVG(COMPETITOR_PRICE),2) AS AVG_COMPETITOR_PRICE
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY;
-- INSIGHT: THE COMPANY'S AVERAGE PRICE MATCHES THE COMPETITION, SIGNIFYING THAT PRICE IS NOT A MARKET DIFFERENTIATOR. 
--          TO WIN, THE BUSINESS MUST COMPETE ON SUPPLY CHAIN SPEED, RELIABILITY, AND EFFICIENCY RATHER THAN COST.

-- 7 MONTHLY ORDER COUNT TREND 
SELECT MONTH,COUNT(ORDER_ID) AS TOTAL_ORDERS_PLACED
FROM SUPPLY_DATA
GROUP BY MONTH
ORDER BY MONTH;
-- INSIGHT: THE TOTAL NUMBER OF ORDERS PLACED IS ROUGHLY SAME ACROSS ALL MONTHS WITH, MONTH 10 VIZ. OCTOBER RECORDS THE HIGHEST NUMBER OF ORDERS 
--          AND MONTH 2 FEBRUARY RECORDS THE LOWEST.


-- 8. TOTAL STOCKOUT INCIDENTS BY WAREHOUSE
SELECT WAREHOUSE_ID,
		SUM(STOCKOUT_FLAG) AS STOCKOUTS
FROM SUPPLY_DATA
GROUP BY WAREHOUSE_ID;
-- INSIGHT: WAREHOUSE 4 HAD THE HIGHEST NUMBER OF STOCKOUT INCIDENTS WHERE AS WAREHOUSE 3 HAD THE LOWEST. 


-- 9. AVERAGE LEAD TIME BY SHIPPING MODE 
SELECT SHIPPING_MODE, AVG(LEAD_TIME_DAYS) AS AVG_LEAD_TIME
FROM SUPPLY_DATA
GROUP BY SHIPPING_MODE;
-- INSIGHT: ALL THREE SHIPPING MODES HAVE ALMOST SAME AVERAGE LEAD TIME DAYS ROUGHLY 18 DAYS, 
--          SIGNIFYING THAT TRANSPORTATION IS RELATIVELY BALANCED WITH NO SINGLE MODE SIGNIFICANTLY OUTPERFORMING OTHERS.

 -- 10. CARBON EMISSIONS BY SHIPPING MODE
 SELECT SHIPPING_MODE, ROUND(SUM(CARBON_EMISSION),2) AS TOTAL_CARBON_EMISSIONS
 FROM SUPPLY_DATA
 GROUP BY SHIPPING_MODE
 ORDER BY TOTAL_CARBON_EMISSIONS DESC;
-- INSIGHT: AMONG THE THREE SHIPPING MODES THE AIR TRANSPORT HAS THE HIGHEST TOTAL CARBON EMISSIONS OF 3000389.77 UNITS 
--          AND SEA TRANSPORT HAS LEAST OF 1028153.87 UNITS.

-- 11. AVERAGE SUPPLIER RELIABILITY ACROSS ALL REGIONS
SELECT REGION, ROUND(AVG(SUPPLIER_RELIABILITY),2) AS AVG_RELIABILITY
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY AVG_RELIABILITY DESC;
-- INSIGHT: SUPPLIER RELIABILITY IS ALMOST UNIFROM ACCROSS ALL REGIONS, HOWEVER NORTH AMERICA HAS THE HIGHEST RELIABILITY WHEREAS EUROPE HAS LEAST.

-- 12. PRODUCT CATEGORY WHICH FACES MOST STOCKOUTS
SELECT PRODUCT_CATEGORY, COUNT(*) AS STOCKOUT_ORDERS 
FROM SUPPLY_DATA
WHERE STOCKOUT_FLAG=1
GROUP BY PRODUCT_CATEGORY
ORDER BY STOCKOUT_ORDERS DESC;
-- INSIGHT: FASHION PRODUCTS HAVE MORE STOCKOUT AMONG ALL CATEGORIES AND BEAUTY PRODUCTS HAS THE LEAST STOCKOUT INCIDENTS.

-- 13. TOP 5 COUNTRIES WITH HIGHEST AVERAGE RETURN RATE
SELECT COUNTRY, ROUND(AVG(RETURN_RATE),4) AS AVG_RETURN_RATE
FROM SUPPLY_DATA
GROUP BY COUNTRY
ORDER BY AVG_RETURN_RATE
LIMIT 5;
-- INSIGHT: THE RETURN RATE IS ALSO ALMOST UNIFORM ACCROSS ALL COUNTRIES BUT THE TOP 5 ARE JAPAN, FOLLOWED BY CANADA, INDIA, UK AND FRANCE.

-- 14. RANKING BRANDS BY REVENUE WITHIN EACH REGION
SELECT REGION, BRAND,
	ROUND(SUM(HISTORICAL_SALES * PRODUCT_PRICE * (1 - DISCOUNT_RATE)),2) AS TOTAL_REVENUE,
RANK() OVER (
			PARTITION BY REGION
            ORDER BY SUM(HISTORICAL_SALES * PRODUCT_PRICE * (1 - DISCOUNT_RATE)) DESC
            ) AS BRAND_RANK
		FROM SUPPLY_DATA
        GROUP BY REGION, BRAND;
-- INSIGHT: BRAND PERFORMANCE VARIES SIGNIFICANTLY BY REGION, WITH BRAND_C DOMINATING REVENUE IN BOTH ASIA-PACIFIC AND EUROPE, 
--          WHILE BRAND_E CONSISTENTLY UNDERPERFORMS AS THE LOWEST REVENUE GENERATOR IN ASIA-PACIFIC, EUROPE, AND THE MIDDLE EAST. 
--          IN CONTRAST, THE AMERICAS SHOW DIVERGING PATTERNS, WITH BRAND_A LEADING IN LATIN AMERICA BUT COMPROMISING PERFORMANCE 
--          AS THE WEAKEST LINK IN NORTH AMERICA, WHERE BRAND_B LEADS REVENUE GENERATION.

-- 15. PERCENTAGE OF ORDERS PRICED ABOVE THEIR CATEGIRY AVERAGE
SELECT ORDER_ID, PRODUCT_CATEGORY, PRODUCT_PRICE 
FROM SUPPLY_DATA S 
WHERE PRODUCT_PRICE> 
		(SELECT AVG(PRODUCT_PRICE) 
			FROM SUPPLY_DATA S1 WHERE S1.PRODUCT_CATEGORY =S.PRODUCT_CATEGORY);
 -- INSIGHT: A SIGNIFICANT NUMBER OF ORDERS WERE PRICED ABOVE THEIR RESPECTIVE CATEGORY AVERAGE, 
 --          INDICATING THE PRESENCE OF PREMIUM-PRICED PRODUCTS ACROSS MULTIPLE CATEGORIES. 
 --          THIS SUGGESTS CUSTOMERS ARE WILLING TO PURCHASE HIGHER-PRICED ITEMS, POTENTIALLY CONTRIBUTING TO INCREASED REVENUE AND PROFIT MARGINS.   

 -- 16. REGIONS ABOVE GLOBAL AVERAGE LOGISTICS COST
 SELECT REGION,ROUND(SUM(TOTAL_LOGISTICS_COST),2) AS TOTAL_LOGISTICS
 FROM SUPPLY_DATA
 GROUP BY REGION
 HAVING SUM(TOTAL_LOGISTICS_COST)>
		(SELECT AVG(TOTAL_LOGISTICS_COST)
        FROM SUPPLY_DATA)
ORDER BY SUM(TOTAL_LOGISTICS_COST)
LIMIT 2;
-- INSIGHT: MIDDLE EAST AND NORTH AMERICA ARE THE TOP 2 REGIONS WHERE TOTAL LOGISTICS COST IS MORE THAN THE GLOBAL AVRAGE LOGISTICS COST.
        

-- 17. HOW EFFICIENTLY IS EACH WAREHOUSE UTILIZING ITS CAPACITY RELATIVE TO ITS LOGISTICS COSTS?
SELECT
    WAREHOUSE_ID,
    ROUND(AVG(TOTAL_LOGISTICS_COST),2) AS AVG_COST,
    ROUND(AVG(INVENTORY_LEVEL / WAREHOUSE_CAPACITY) * 100,2) AS UTILIZATION_PERCENT
FROM SUPPLY_DATA
GROUP BY WAREHOUSE_ID
ORDER BY WAREHOUSE_ID;
-- INSIGHT: WAREHOUSE UTILIZATION AND LOGISTICS COSTS REMAIN CONSISTENT ACROSS THE NETWORK,SIGNIFYING BALANCED INVENTORY DISTRIBUTION AND EVEN OPERATIONAL WORKLOADS.
--          THIS EQUILIBRIUM INDICATES EFFECTIVE NETWORK CAPACITY PLANNING AND MINIMIZES THE RISK OF REGIONAL BOTTLENECKS.

-- 18. WHICH PRODUCT CATEGORIES ATTRACT THE HIGHEST WEBSITE TRAFFIC?
SELECT PRODUCT_CATEGORY,
		ROUND(AVG(WEBSITE_TRAFFIC),2) AS AVG_WEBSITE_VISITS
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY AVG_WEBSITE_VISITS DESC;
-- INSIGHTS: WEBSITE TRAFFIC REMAINS HIGHLY CONSISTENT ACROSS ALL PRODUCT CATEGORIES, AVERAGING AROUND 25,000 VISITS. 
--           BEAUTY OUTPERFORMS AS THE TOP TRAFFIC GENERATOR AT 25,983 VISITS, WHILE FASHION REPRESENTS THE LOWEST VOLUME AT 25,306 VISITS.

-- 19. DO PRODUCTS WITH HIGHER WEBSITE TRAFFIC GENERATE HIGHER SALES?
SELECT PRODUCT_CATEGORY,
		ROUND(AVG(HISTORICAL_SALES),2) AS AVG_SALES,
        ROUND(AVG(WEBSITE_TRAFFIC),2) AS AVG_WEBSITE_VISITS
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY AVG_WEBSITE_VISITS DESC;
-- INSIGHT: HIGHER WEBSITE TRAFFIC DOES NOT GUARANTEE HIGHER SALES, AS CONVERSION RATES AND AVERAGE SALES REMAIN DECOUPLED FROM TRAFFIC VOLUMES ACROSS CATEGORIES. 
--          FOR EXAMPLE, ELECTRONICS GENERATES SIGNIFICANTLY HIGHER WEBSITE TRAFFIC THAN FASHION (25,823 VS. 25,306 VISITS) 
--          BUT ACTUALLY YIELDS LOWER AVERAGE SALES (1,514.96 VS. 1,545.99 UNITS), HIGHLIGHTING A GAP IN CONVERSION EFFICIENCY.

-- 20. WHICH CUSTOMER SEGMENT HAS THE HIGHEST CONVERSION RATE?
SELECT CUSTOMER_SEGMENT, 
		ROUND(AVG(CONVERSION_RATE),4) AS AVG_CONVERSION_RATE
FROM SUPPLY_DATA
GROUP BY CUSTOMER_SEGMENT;
-- INSIGHT: CONVERDION RATE IS UNIFORM ACROSS BOTH SEGMENTS HOWEVER WHOLESALE SEGMENTS RECORDS MARGINALLY HIGHER CONVERSION_RATE THAN RETAIL SEGMENT.

-- 21. WHICH PRODUCT CATEGORIES HAVE THE STRONGEST MARKET DEMAND?
SELECT PRODUCT_CATEGORY,
       ROUND(AVG(SEARCH_TREND_INDEX),2) AS AVG_TREND
FROM SUPPLY_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY AVG_TREND DESC;
-- INISGHT: DEMAND REMAINS ROUGHLY UNIFORM ACROSS ALL PRODUCT CATEGORIES, INDICATING A BALANCED MARKET DESIRE. WITHIN THIS CONSISTENT PATTERN, 
--          HOME PRODUCTS EMERGE AS THE HIGHEST IN DEMAND, WHILE ELECTRONICS RANK AS THE LEAST SOUGHT-AFTER CATEGORY IN THE NETWORK.

-- 22. DOES REVENUE INCREASE DURING FESTIVAL PERIODS? 
SELECT FESTIVAL_SEASON,
       ROUND(
           SUM(HISTORICAL_SALES * PRODUCT_PRICE * (1-DISCOUNT_RATE)),
           2
       ) AS REVENUE
FROM SUPPLY_DATA
GROUP BY FESTIVAL_SEASON;
-- INSIGHT: REVENUE DURING NON-FESTIVAL SEASONS IS ALMOST SIX TIMES HIGHER THAN FESTIVAL REVENUE, PROVING THAT THE BUSINESS DRIVES THE BULK OF ITS FINANCIAL GROWTH, 
--          THROUGH SUSTAINED, YEAR-ROUND BASELINE DEMAND RATHER THAN HOLIDAY SPIKES.

-- 23. WHICH REGIONS ARE MOST AFFECTED BY WEATHER CONDITIONS?
SELECT REGION,
       ROUND(AVG(WEATHER_INDEX),4) AS AVG_WEATHER
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY AVG_WEATHER DESC;
-- INSIGHT: WEATHER DISRUPTIONS EXERCISED A SIMILAR IMPACT PATTERN ACROSS ALL REGIONS globally. WITHIN THIS BALANCED TREND, 
--          LOGISTICAL AND OPERATIONAL IMPEDIMENTS PROVED MOST PROMINENT IN LATIN AMERICA, WHILE EUROPE EXPERIENCED THE LEAST SEVERE OPERATIONAL DISRUPTION 
--          FROM WEATHER FACTORS.

-- 24. DOES HIGHER FUEL COST LEAD TO HIGHER LOGISTICS COSTS?
SELECT REGION,
       ROUND(AVG(FUEL_COST_INDEX),2) AS AVG_FUEL_COST,
       ROUND(AVG(TOTAL_LOGISTICS_COST),2) AS AVG_LOGISTICS_COST
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY AVG_FUEL_COST DESC;
-- INSIGHT: HIGHER FUEL COSTS DO NOT DIRECTLY INFLICT HIGHER LOGISTICS COSTS. LATIN AMERICA AND EUROPE BOTH SHARE THE HIGHEST AVERAGE FUEL COST (95.38),
--          YET EUROPE INCURS THE MOST EXPENSIVE OVERALL LOGISTICS (7,841.08) COMPARED TO LATIN AMERICA (7,677.39), 
--          PROVING THAT OTHER LOGISTICAL VARIABLES DRIVE TOTAL COSTS.

-- 25. WHICH REGIONS EXPERIENCE THE HIGHEST PORT CONGESTION?
SELECT REGION,
       ROUND(AVG(PORT_CONGESTION_INDEX),2) AS AVG_CONGESTION
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY AVG_CONGESTION DESC;
-- INSIGHT: ALTHOUGH AVERAGE CONGESTION IS ALMOST SAME BUT EUROPE FACES MOST CONGESTIONS WHILE ASIA PACIFIC REGION FACES THE LEAST.

-- 26. WHICH SHIPPING MODE HAS THE BEST ON-TIME DELIVERY PERFORMANCE?
SELECT SHIPPING_MODE,
SUM(CASE WHEN DELIVERY_TIME_ONTIME=1 THEN 1 ELSE 0 END) AS ON_TIME_DELIVERY,
SUM(CASE WHEN DELIVERY_TIME_ONTIME=0 THEN 1 ELSE 0 END) AS DELAYED_DELIVERY
FROM SUPPLY_DATA
GROUP BY SHIPPING_MODE;
-- INSIGHT: AIR FREIGHT HAS THE BEST ON-TIME PERFORMANCE (1,967 SUCCESSES, 6,361 DELAYS), WHILE SEA FREIGHT HAS THE WORST (6,484 DELAYS). CRITICALLY, 
--          DELAYS OVERWHELMINGLY DOMINATE EVERY SINGLE SHIPPING MODE, SHOWING THAT SYSTEMIC LOGISTICS BOTTLENECKS AFFECT THE ENTIRE NETWORK 
--          REGARDLESS OF THE TRANSPORT METHOD CHOSEN.

-- 27. WHICH REGION HAS THE MOST DELAYED DELIVERIES
SELECT REGION,
SUM(CASE WHEN DELIVERY_TIME_ONTIME=1 THEN 1 ELSE 0 END) AS ON_TIME_DELIVERY,
SUM(CASE WHEN DELIVERY_TIME_ONTIME=0 THEN 1 ELSE 0 END) AS DELAYED_DELIVERY
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY DELAYED_DELIVERY DESC;
-- INSIGHT: LATIN AMERICA HAS RECORDED THE HIGHEST NUMBER OF DELAYED AS WELL AS ONTIME DELIVERIES.

-- 28. DOES HIGHER PORT CONGESTION REDUCE ON-TIME DELIVERY PERFORMANCE?
SELECT REGION,
			ROUND(AVG(PORT_CONGESTION_INDEX),2) AS AVG_CONGESTION,
            SUM(CASE WHEN DELIVERY_TIME_ONTIME=1 THEN 1 ELSE 0 END) AS ON_TIME_DELIVERY,
			SUM(CASE WHEN DELIVERY_TIME_ONTIME=0 THEN 1 ELSE 0 END) AS DELAYED_DELIVERY
FROM SUPPLY_DATA
GROUP BY REGION
ORDER BY DELAYED_DELIVERY DESC;
-- INSIGHT: PORT CONGESTION DOES NOT DIRECTLY REDUCE ON-TIME PERFORMANCE. EUROPE HAS THE HIGHEST CONGESTION (50.14) YET FEWER DELAYS (3,835) 
--          THAN LATIN AMERICA (3,915). CRITICALLY, DELAYS SYSTEMICALLY OUTNUMBER ON-TIME DELIVERIES 4-TO-1 IN EVERY REGION, 
--          PROVING THAT FREIGHT BOTTLENECKS ARE DRIVEN BY FACTORS BEYOND PORT CONGESTION ALONE.


-- 29. WHAT IS THE ON TIME DELEIVERIES PERCENTAGE AND DELAYED DELIVERY PERCENTAGE IN EVERY REGION
SELECT REGION,
		ROUND((SUM(CASE WHEN DELIVERY_TIME_ONTIME=1 THEN 1 ELSE 0 END)*100)/COUNT(*),2)
        AS ONTIME_PERCENTAGE,
        ROUND((SUM(CASE WHEN DELIVERY_TIME_ONTIME=0 THEN 1 ELSE 0 END)*100)/COUNT(*),2)
        AS DELAYED_PERCENTAGE
FROM SUPPLY_DATA
GROUP BY REGION;
-- INSIGHT:DELAYED DELIVERIES CONSISTENTLY EXCEEDED ON-TIME DELIVERIES ACROSS ALL REGIONS, 
--         WITH THE DELAYED DELIVERY PERCENTAGE BEING APPROXIMATELY 3.5 TIMES HIGHER THAN THE ON-TIME DELIVERY PERCENTAGE. 
--         THIS INDICATES A WIDESPREAD DELIVERY PERFORMANCE ISSUE ACROSS THE SUPPLY CHAIN NETWORK.



-- TOP 5 ANALYTICAL FINDINGS

-- 1. SYSTEMIC GLOBAL DELIVERY DELAYS: 
--            DELIVERY PERFORMANCE IS CRITICALLY WEAK ACROSS ALL GLOBAL REGIONS, WITH DELAYED SHIPMENTS CONSISTENTLY OUTNUMBERING ON-TIME DELIVERIES 
--            BY A FACTOR OF NEARLY 3.5 TO 1.

-- 2. COMPETITIVE PRICING ALIGNMENT: 
--            THE COMPANY MAINTAINS A STRONG MARKET POSITION REGARDING PRICING, AS AVERAGE PRICE POINTS REMAIN HIGHLY COMPETITIVE 
--            AND CLOSELY ALIGNED WITH RIVAL COMPANIES.

-- 3. REGION-SPECIFIC BRAND DYNAMICS: 
--            BRAND PERFORMANCE VARIES SIGNIFICANTLY BY REGION; A BRAND THAT UNDERPERFORMS IN ONE REGION OFTEN EXCELS IN ANOTHER, 
--            HIGHLIGHTING DISTINCT REGIONAL VARIATIONS IN CUSTOMER DEMAND AND PREFERENCE.

-- 4. TRAFFIC AND SALES DECOUPLING: 
--            HIGHER WEBSITE TRAFFIC DOES NOT AUTOMATICALLY GUARANTEE INCREASED SALES, REVEALING A GAP BETWEEN CUSTOMER ACQUISITION/BROWSING 
--            AND ACTUAL PURCHASING CONVERSION.

-- 5. BASELINE REVENUE DOMINANCE: 
--           IN A SURPRISING TREND, REVENUE GENERATED DURING NON-FESTIVAL SEASONS IS APPROXIMATELY 6 TIMES HIGHER THAN FESTIVAL SEASON REVENUE, 
--           PROVING THE BUSINESS RELIES HEAVILY ON SUSTAINED, YEAR-ROUND BASELINE DEMAND RATHER THAN SHORT-TERM HOLIDAY SPIKES.


--                                                              END OF REPORT